/// AUTOSTAGE's deterministic preprocessing: walks dialogue-only input text (valid NovaScript
/// `Speaker::text` lines, no staging calls yet) and derives a small node graph - which node each
/// line belongs to, who's on stage at each point, and any user-supplied technical requirement for
/// that line - using a small set of explicit marker conventions. None of this is "scene"-shaped:
/// a node boundary is about navigation granularity (can the engine jump here?), not about
/// background stability, so the default with no branching markers is a single node spanning the
/// whole input, however many backgrounds it touches.
///
/// - `#loc: <path>` is a sticky per-moment annotation (not a node boundary) marking what the
///   background should be from this point on, until changed or the node resets.
/// - `#hnt: <text>` is a sticky technical requirement ("用什么音乐/动画" etc) that the model must
///   honor, not just consider - it stays active for every following line until either the next
///   `#loc:` (does NOT clear it - only `#hnt:` itself does, see below) or the next `#hnt:`
///   (replaces it, or clears it if its value is empty).
/// - `#cast: +<name>` / `#cast: -<name>` is an explicit on-stage roster delta: an author-stated
///   fact ("小王出现"/"小王离开") that must be captured as ground truth rather than left to the
///   speaker-inference heuristic alone. Mutates the same roster speaker-inference already grows.
/// - `#seq:` (no value) toggles a "performance sequence" span open/closed, mirroring `#hnt:`'s
///   empty-clears convention as a pure two-state toggle (no nesting). Inside an open span every
///   line is raw passthrough - copied verbatim, not parsed as any marker or dialogue at all - since
///   performance-driven content is hand-authored by the author, never generated by AUTOSTAGE.
/// - `#branch:` ends the current node's narrative content and declares its terminator to be a
///   `branch()` call, populated by one or more following `#opt: <dest> | <text> | <mode> | <cond>`
///   lines (pipe-delimited, only `dest` required).
/// - `#node: <name>` starts a new, explicitly-named node (reachable only via some `#opt:`'s
///   `dest`, or a `#jump:`). `on_stage`/`background`/`active_hint` all reset entering any
///   `#node:` block, since nothing about prior state is statically knowable at an arbitrary jump
///   target.
/// - `#jump: <dest>` is an explicit `jump_to()` terminator, enabling merge-back (multiple nodes
///   can each `#jump:` to the same convergence node name).
///
/// Any other line starting with `#` is a plain authoring comment - silently dropped.
///
/// The resulting timeline feeds both `build_node_skeleton` (the structural scaffold) and the
/// AUTOSTAGE prompt, so the model only ever stages objects the timeline says are actually present.
const LOCATION_MARKER_PREFIX: &str = "#loc:";
const HINT_MARKER_PREFIX: &str = "#hnt:";
const CAST_MARKER_PREFIX: &str = "#cast:";
const SEQUENCE_MARKER_PREFIX: &str = "#seq:";
const BRANCH_MARKER: &str = "#branch:";
const OPTION_MARKER_PREFIX: &str = "#opt:";
const NODE_MARKER_PREFIX: &str = "#node:";
const JUMP_MARKER_PREFIX: &str = "#jump:";

const SKELETON_STAGING_TODO: &str = "# TODO: 在这里补充这一拍的演出（show/tint/vfx/play 等）";
pub const SEQUENCE_BEGIN_MARKER: &str = "# vvn:seq begin";
pub const SEQUENCE_END_MARKER: &str = "# vvn:seq end";

#[derive(Debug, Clone, PartialEq)]
pub struct StageMoment {
    pub dialogue_line_index: usize,
    pub text: String,
    pub speaker: Option<String>,
    pub on_stage: Vec<String>,
    pub background: Option<String>,
    pub active_hint: Option<String>,
}

#[derive(Debug, Clone, PartialEq)]
pub enum NodeItem {
    Moment(StageMoment),
    /// Verbatim, newline-joined author content from inside a `#seq:` span. Never parsed, never
    /// touched by AUTOSTAGE's staging-fill model - `build_node_skeleton` wraps it with
    /// `SEQUENCE_BEGIN_MARKER`/`SEQUENCE_END_MARKER` so the lifecycle tracker can recognize it.
    RawPassthrough(String),
}

#[derive(Debug, Clone, PartialEq)]
pub struct BranchOption {
    pub dest: String,
    pub text: Option<String>,
    pub mode: Option<String>,
    pub cond: Option<String>,
}

#[derive(Debug, Clone, PartialEq)]
pub enum NodeTerminator {
    End,
    Branch(Vec<BranchOption>),
    Jump(String),
}

#[derive(Debug, Clone, PartialEq)]
pub struct NodeBlock {
    /// `None` for the implicit main/entry node (`timeline.nodes[0]`); `Some(name)` for a node
    /// declared via `#node: <name>`.
    pub name: Option<String>,
    pub items: Vec<NodeItem>,
    pub terminator: NodeTerminator,
}

#[derive(Debug, Clone, PartialEq)]
pub struct WorldStateTimeline {
    /// `nodes[0]` is always the implicit main node, present even if empty.
    pub nodes: Vec<NodeBlock>,
    pub distinct_speakers: Vec<String>,
}

#[derive(Debug, Clone, PartialEq)]
pub enum WorldStateError {
    /// `#opt:` with no preceding open `#branch:` in the current node.
    OptWithoutBranch { line_index: usize },
    /// `#branch:` declared but the node moved on (next `#branch:`/`#jump:`/`#node:`/EOF) with
    /// zero `#opt:` lines collected - a `branch([])` call would be vacuous/broken.
    BranchWithNoOptions { line_index: usize },
    /// `#opt:` whose `dest` field is blank after trimming.
    EmptyOptDest { line_index: usize },
    /// A `#node:` name that's already taken - by an earlier `#node:` declaration, or by the main
    /// node's own label (`base_label`).
    DuplicateNodeName { name: String, line_index: usize },
    /// A `#opt:`/`#jump:` `dest` that doesn't match any `#node:`-declared name anywhere in the
    /// file (checked after the whole file is parsed, so forward references are fine).
    DanglingDest { dest: String, from_node: Option<String>, line_index: usize },
}

impl WorldStateError {
    pub fn describe(&self) -> String {
        match self {
            WorldStateError::OptWithoutBranch { line_index } => {
                format!("第 {line_index} 行：`#opt:` 前面没有对应的 `#branch:`，不知道这个选项属于哪个分支。")
            }
            WorldStateError::BranchWithNoOptions { line_index } => {
                format!("第 {line_index} 行附近：`#branch:` 声明了分支，但一个 `#opt:` 选项都没有给。")
            }
            WorldStateError::EmptyOptDest { line_index } => {
                format!("第 {line_index} 行：`#opt:` 的目标节点名（第一个字段）是空的。")
            }
            WorldStateError::DuplicateNodeName { name, line_index } => {
                format!("第 {line_index} 行：节点名 \"{name}\" 和前面已经出现过的节点重名了。")
            }
            WorldStateError::DanglingDest { dest, from_node, line_index } => {
                let from = from_node.as_deref().unwrap_or("主节点");
                format!("第 {line_index} 行（节点 \"{from}\" 内）：目标节点 \"{dest}\" 在全文里找不到对应的 `#node:` 声明。")
            }
        }
    }
}

struct CastDelta {
    name: String,
    present: bool,
}

enum TerminatorChoice {
    Default,
    Branch,
    Jump(String),
}

fn parse_location_marker(line: &str) -> Option<String> {
    let rest = line.strip_prefix(LOCATION_MARKER_PREFIX)?;
    let value = rest.trim();
    if value.is_empty() {
        None
    } else {
        Some(value.to_string())
    }
}

/// `Some(None)` means "this is a hint marker, and it explicitly clears the active hint" (an empty
/// `#hnt:` value) - distinct from `None`, which means "this line isn't a hint marker at all".
fn parse_hint_marker(line: &str) -> Option<Option<String>> {
    let rest = line.strip_prefix(HINT_MARKER_PREFIX)?;
    let value = rest.trim();
    if value.is_empty() {
        Some(None)
    } else {
        Some(Some(value.to_string()))
    }
}

fn parse_cast_marker(line: &str) -> Option<CastDelta> {
    let rest = line.strip_prefix(CAST_MARKER_PREFIX)?;
    let value = rest.trim();
    if let Some(name) = value.strip_prefix('+') {
        let name = name.trim();
        if name.is_empty() {
            return None;
        }
        return Some(CastDelta { name: name.to_string(), present: true });
    }
    if let Some(name) = value.strip_prefix('-') {
        let name = name.trim();
        if name.is_empty() {
            return None;
        }
        return Some(CastDelta { name: name.to_string(), present: false });
    }
    None
}

/// `#seq:` is a pure two-state toggle with no value - any non-empty trailing text is ignored
/// (not an error), so an author writing `#seq: 第五法式` as a descriptive label still toggles the
/// span correctly. There's no nesting: a second `#seq:` while one is already open always closes
/// it, never opens a nested one.
fn parse_sequence_marker(line: &str) -> bool {
    line.starts_with(SEQUENCE_MARKER_PREFIX)
}

fn parse_branch_marker(line: &str) -> bool {
    line == BRANCH_MARKER
}

/// `dest` is required but this function doesn't validate it - an `#opt:` with a blank `dest`
/// still returns `Some(BranchOption { dest: String::new(), .. })` so the caller can centralize
/// `WorldStateError` construction, matching how `derive_world_state_timeline` already centralizes
/// every other state-transition decision rather than scattering it into parsers.
fn parse_option_marker(line: &str) -> Option<BranchOption> {
    let rest = line.strip_prefix(OPTION_MARKER_PREFIX)?;
    let mut fields = rest.split('|').map(|field| field.trim());
    let dest = fields.next().unwrap_or("").to_string();
    let text = fields.next().filter(|field| !field.is_empty()).map(str::to_string);
    let mode = fields.next().filter(|field| !field.is_empty()).map(str::to_string);
    let cond = fields.next().filter(|field| !field.is_empty()).map(str::to_string);
    Some(BranchOption { dest, text, mode, cond })
}

fn parse_node_marker(line: &str) -> Option<String> {
    let rest = line.strip_prefix(NODE_MARKER_PREFIX)?;
    let name = rest.trim();
    if name.is_empty() {
        None
    } else {
        Some(name.to_string())
    }
}

fn parse_jump_marker(line: &str) -> Option<String> {
    let rest = line.strip_prefix(JUMP_MARKER_PREFIX)?;
    let dest = rest.trim();
    if dest.is_empty() {
        None
    } else {
        Some(dest.to_string())
    }
}

/// Mirrors novascript-reference.md §2.1: `显示名::对话内容` or `显示名//隐藏名::对话内容`, both
/// halfwidth `::` and fullwidth `：：` accepted. Plain text lines with no separator are narration
/// (no speaker) - `None` here, not an error, since narration is still a valid dialogue-only line.
fn parse_speaker(line: &str) -> Option<String> {
    let separator_index = line.find("::").or_else(|| line.find("：："))?;
    let display_part = &line[..separator_index];
    let display_name = display_part.split("//").next().unwrap_or(display_part).trim();
    if display_name.is_empty() {
        None
    } else {
        Some(display_name.to_string())
    }
}

/// A `#branch:` that's about to be abandoned (a new `#branch:`/`#jump:`/`#node:`/EOF arrives)
/// without ever collecting an `#opt:` line is always a mistake worth surfacing immediately,
/// rather than silently producing a vacuous `branch([])`.
fn check_branch_not_left_empty(
    terminator_choice: &TerminatorChoice,
    branch_options: &[BranchOption],
    line_index: usize,
) -> Result<(), WorldStateError> {
    if matches!(terminator_choice, TerminatorChoice::Branch) && branch_options.is_empty() {
        Err(WorldStateError::BranchWithNoOptions { line_index })
    } else {
        Ok(())
    }
}

fn finalize_node(
    name: Option<String>,
    items: Vec<NodeItem>,
    terminator_choice: &TerminatorChoice,
    branch_options: &[BranchOption],
    flush_line_index: usize,
) -> Result<NodeBlock, WorldStateError> {
    let terminator = match terminator_choice {
        TerminatorChoice::Default => NodeTerminator::End,
        TerminatorChoice::Branch => {
            if branch_options.is_empty() {
                return Err(WorldStateError::BranchWithNoOptions { line_index: flush_line_index });
            }
            NodeTerminator::Branch(branch_options.to_vec())
        }
        TerminatorChoice::Jump(dest) => NodeTerminator::Jump(dest.clone()),
    };
    Ok(NodeBlock { name, items, terminator })
}

/// Walks the dialogue-only input top to bottom, building a small node graph. The default (no
/// `#branch:`/`#node:` used at all) is a single main node spanning every line - node-splitting is
/// opt-in, triggered only by explicit branching markers, never by `#loc:` background changes.
pub fn derive_world_state_timeline(
    dialogue_only_text: &str,
    base_label: &str,
) -> Result<WorldStateTimeline, WorldStateError> {
    let lines: Vec<&str> = dialogue_only_text.lines().collect();

    let mut nodes: Vec<NodeBlock> = Vec::new();
    let mut current_name: Option<String> = None;
    let mut current_items: Vec<NodeItem> = Vec::new();
    let mut terminator_choice = TerminatorChoice::Default;
    let mut branch_options: Vec<BranchOption> = Vec::new();

    let mut current_background: Option<String> = None;
    let mut on_stage: Vec<String> = Vec::new();
    let mut active_hint: Option<String> = None;

    let mut in_sequence = false;
    let mut raw_buffer: Vec<String> = Vec::new();

    let mut distinct_speakers: Vec<String> = Vec::new();
    let mut dest_references: Vec<(String, Option<String>, usize)> = Vec::new();

    for (index, raw_line) in lines.iter().enumerate() {
        if in_sequence {
            if parse_sequence_marker(raw_line.trim()) {
                if !raw_buffer.is_empty() {
                    current_items.push(NodeItem::RawPassthrough(raw_buffer.join("\n")));
                    raw_buffer.clear();
                }
                in_sequence = false;
            } else {
                raw_buffer.push((*raw_line).to_string());
            }
            continue;
        }

        let trimmed = raw_line.trim();
        if trimmed.is_empty() {
            continue;
        }

        if parse_sequence_marker(trimmed) {
            in_sequence = true;
            raw_buffer.clear();
            continue;
        }

        if let Some(background) = parse_location_marker(trimmed) {
            current_background = Some(background);
            continue;
        }

        if let Some(hint) = parse_hint_marker(trimmed) {
            active_hint = hint;
            continue;
        }

        if let Some(delta) = parse_cast_marker(trimmed) {
            if delta.present {
                if !on_stage.iter().any(|existing| existing == &delta.name) {
                    on_stage.push(delta.name);
                }
            } else {
                on_stage.retain(|existing| existing != &delta.name);
            }
            continue;
        }

        if parse_branch_marker(trimmed) {
            check_branch_not_left_empty(&terminator_choice, &branch_options, index)?;
            terminator_choice = TerminatorChoice::Branch;
            branch_options.clear();
            continue;
        }

        if let Some(option) = parse_option_marker(trimmed) {
            if !matches!(terminator_choice, TerminatorChoice::Branch) {
                return Err(WorldStateError::OptWithoutBranch { line_index: index });
            }
            if option.dest.is_empty() {
                return Err(WorldStateError::EmptyOptDest { line_index: index });
            }
            dest_references.push((option.dest.clone(), current_name.clone(), index));
            branch_options.push(option);
            continue;
        }

        if let Some(dest) = parse_jump_marker(trimmed) {
            check_branch_not_left_empty(&terminator_choice, &branch_options, index)?;
            dest_references.push((dest.clone(), current_name.clone(), index));
            terminator_choice = TerminatorChoice::Jump(dest);
            continue;
        }

        if let Some(name) = parse_node_marker(trimmed) {
            check_branch_not_left_empty(&terminator_choice, &branch_options, index)?;
            let finished = finalize_node(
                current_name.take(),
                std::mem::take(&mut current_items),
                &terminator_choice,
                &branch_options,
                index,
            )?;
            nodes.push(finished);

            if name == base_label || nodes.iter().any(|node| node.name.as_deref() == Some(name.as_str())) {
                return Err(WorldStateError::DuplicateNodeName { name, line_index: index });
            }

            current_name = Some(name);
            terminator_choice = TerminatorChoice::Default;
            branch_options.clear();
            current_background = None;
            on_stage = Vec::new();
            active_hint = None;
            continue;
        }

        if trimmed.starts_with('#') {
            continue;
        }

        let speaker = parse_speaker(trimmed);
        if let Some(name) = &speaker {
            if !on_stage.iter().any(|existing| existing == name) {
                on_stage.push(name.clone());
            }
            if !distinct_speakers.iter().any(|existing| existing == name) {
                distinct_speakers.push(name.clone());
            }
        }
        current_items.push(NodeItem::Moment(StageMoment {
            dialogue_line_index: index,
            text: trimmed.to_string(),
            speaker,
            on_stage: on_stage.clone(),
            background: current_background.clone(),
            active_hint: active_hint.clone(),
        }));
    }

    if in_sequence && !raw_buffer.is_empty() {
        current_items.push(NodeItem::RawPassthrough(raw_buffer.join("\n")));
    }

    let eof_index = lines.len();
    check_branch_not_left_empty(&terminator_choice, &branch_options, eof_index)?;
    let last_node = finalize_node(current_name.take(), current_items, &terminator_choice, &branch_options, eof_index)?;
    nodes.push(last_node);

    let declared_names: Vec<&str> = nodes.iter().filter_map(|node| node.name.as_deref()).collect();
    for (dest, from_node, line_index) in &dest_references {
        if !declared_names.contains(&dest.as_str()) {
            return Err(WorldStateError::DanglingDest {
                dest: dest.clone(),
                from_node: from_node.clone(),
                line_index: *line_index,
            });
        }
    }

    Ok(WorldStateTimeline { nodes, distinct_speakers })
}

/// Builds a deterministic, structurally-closed NovaScript skeleton: one `label()` block per
/// `NodeBlock` (one in the common no-branching case, spanning the whole input regardless of how
/// many backgrounds it touches), a staging placeholder before each dialogue line (carrying that
/// moment's `#hnt:` requirement, if any), `#seq:` spans wrapped in dedicated empty bracketing
/// blocks carrying the `SEQUENCE_BEGIN_MARKER`/`SEQUENCE_END_MARKER` comments the lifecycle
/// tracker looks for, and each node's declared terminator (`is_end()`/`jump_to()`/`branch()`).
/// The model's job is filling in the placeholders, never inventing structure.
pub fn build_node_skeleton(timeline: &WorldStateTimeline, base_label: &str) -> String {
    let mut output = String::new();
    let node_count = timeline.nodes.len();
    // Tracks whether the very first dialogue moment has been emitted yet, so we can inject the
    // UI-initialization calls (set_box / set_text_appear) into that moment's placeholder block.
    // These calls must run before the first dialogue step; they're deterministic requirements,
    // not creative staging, so the skeleton provides them as pre-filled lines rather than leaving
    // them for the model to guess.
    let mut first_moment_emitted = false;

    for (node_index, node) in timeline.nodes.iter().enumerate() {
        let label_name = node.name.clone().unwrap_or_else(|| base_label.to_string());
        output.push_str("@<|\n");
        output.push_str(&format!("label(\"{label_name}\", \"AUTOSTAGE\")\n"));
        if node_index == 0 {
            output.push_str("is_unlocked_start()\n");
        }
        output.push_str("|>\n");

        for item in &node.items {
            match item {
                NodeItem::Moment(moment) => {
                    output.push_str("<|\n");
                    if !first_moment_emitted {
                        // Initialize the dialogue box once, before the first line of text.
                        // set_box picks the layout ("bottom" is the standard full-width bar);
                        // set_text_appear sets the typewriter speed (chars/s, interval, fade).
                        output.push_str("set_box(\"bottom\")\nset_text_appear(2, 30, 0.3)\n");
                        first_moment_emitted = true;
                    }
                    if let Some(hint) = &moment.active_hint {
                        output.push_str(&format!("# Staging Requirement (must be implemented as a function call, cannot be ignored): {hint}\n"));
                    }
                    output.push_str(SKELETON_STAGING_TODO);
                    output.push_str("\n|>\n");
                    output.push_str(&moment.text);
                    output.push_str("\n\n");
                }
                NodeItem::RawPassthrough(raw) => {
                    output.push_str("<|\n");
                    output.push_str(SEQUENCE_BEGIN_MARKER);
                    output.push_str("\n|>\n\n");
                    output.push_str(raw);
                    output.push_str("\n\n<|\n");
                    output.push_str(SEQUENCE_END_MARKER);
                    output.push_str("\n|>\n\n");
                }
            }
        }

        match &node.terminator {
            NodeTerminator::End => {
                // An empty main node whose only declared terminator is End, but there are
                // named nodes after it, means the user started with #branch:/#node: right away
                // with no leading dialogue - the main node should flow into the first named node
                // rather than ending immediately (which would produce a gray screen at launch).
                let auto_jump = node_index == 0
                    && node.items.is_empty()
                    && node_count > 1
                    && timeline.nodes[1].name.is_some();
                if auto_jump {
                    let first_named = timeline.nodes[1].name.as_deref().unwrap();
                    output.push_str(&format!("@<| jump_to(\"{first_named}\") |>\n"));
                } else {
                    output.push_str("@<| is_end() |>\n");
                }
            }
            NodeTerminator::Jump(dest) => output.push_str(&format!("@<| jump_to(\"{dest}\") |>\n")),
            NodeTerminator::Branch(options) => {
                output.push_str("@<| branch([\n");
                for option in options {
                    let mut fields = vec![format!("dest=\"{}\"", option.dest)];
                    if let Some(text) = &option.text {
                        fields.push(format!("text=\"{text}\""));
                    }
                    if let Some(mode) = &option.mode {
                        fields.push(format!("mode=\"{mode}\""));
                    }
                    if let Some(cond) = &option.cond {
                        fields.push(format!("cond=\"{cond}\""));
                    }
                    output.push_str("  {");
                    output.push_str(&fields.join(", "));
                    output.push_str("},\n");
                }
                output.push_str("]) |>\n");
            }
        }

        if node_index + 1 < node_count {
            output.push('\n');
        }
    }

    output
}

#[cfg(test)]
mod tests {
    use super::*;

    fn timeline(text: &str) -> WorldStateTimeline {
        derive_world_state_timeline(text, "ch1_autostage").expect("expected a valid timeline")
    }

    fn main_node(t: &WorldStateTimeline) -> &NodeBlock {
        &t.nodes[0]
    }

    fn moments(node: &NodeBlock) -> Vec<&StageMoment> {
        node.items
            .iter()
            .filter_map(|item| match item {
                NodeItem::Moment(m) => Some(m),
                NodeItem::RawPassthrough(_) => None,
            })
            .collect()
    }

    #[test]
    fn derives_distinct_speakers_in_first_appearance_order() {
        let text = "二宫::你好\n张浅野::早\n二宫::走吧\n";
        let t = timeline(text);
        assert_eq!(t.distinct_speakers, vec!["二宫".to_string(), "张浅野".to_string()]);
    }

    #[test]
    fn narration_lines_have_no_speaker_but_still_become_a_moment() {
        let text = "天色渐暗。\n二宫::该回去了\n";
        let t = timeline(text);
        let m = moments(main_node(&t));
        assert_eq!(m.len(), 2);
        assert_eq!(m[0].speaker, None);
        assert_eq!(m[0].text, "天色渐暗。");
    }

    #[test]
    fn accepts_fullwidth_colon_separator() {
        let t = timeline("二宫：：你好\n");
        assert_eq!(t.distinct_speakers, vec!["二宫".to_string()]);
    }

    #[test]
    fn strips_hidden_name_when_parsing_speaker() {
        let t = timeline("二宫//ergong::你好\n");
        assert_eq!(t.distinct_speakers, vec!["二宫".to_string()]);
    }

    #[test]
    fn generic_comment_lines_are_dropped_and_never_become_a_moment() {
        let t = timeline("# TODO: 这段还没想好怎么写\n二宫::你好\n");
        let m = moments(main_node(&t));
        assert_eq!(m.len(), 1);
        assert_eq!(m[0].text, "二宫::你好");
    }

    #[test]
    fn hint_applies_to_every_line_until_replaced() {
        let text = "#hnt: 配雨声环境音\n二宫::外面下雨了呢\n张浅野::是啊\n";
        let t = timeline(text);
        let m = moments(main_node(&t));
        assert_eq!(m[0].active_hint, Some("配雨声环境音".to_string()));
        assert_eq!(m[1].active_hint, Some("配雨声环境音".to_string()));
    }

    #[test]
    fn hint_is_replaced_by_a_later_hint() {
        let text = "#hnt: 配雨声\n二宫::外面下雨了呢\n#hnt: 配雷声\n张浅野::打雷了\n";
        let t = timeline(text);
        let m = moments(main_node(&t));
        assert_eq!(m[0].active_hint, Some("配雨声".to_string()));
        assert_eq!(m[1].active_hint, Some("配雷声".to_string()));
    }

    #[test]
    fn empty_hint_marker_explicitly_clears_active_hint() {
        let text = "#hnt: 配雨声\n二宫::外面下雨了呢\n#hnt:\n张浅野::雨停了\n";
        let t = timeline(text);
        let m = moments(main_node(&t));
        assert_eq!(m[0].active_hint, Some("配雨声".to_string()));
        assert_eq!(m[1].active_hint, None);
    }

    // --- Correction 1: #loc: demoted to an annotation, no longer splits nodes ---

    #[test]
    fn single_node_default_when_no_branch_or_node_markers_present() {
        let text = "#loc: backgrounds/room\n二宫::你好\n\n#loc: backgrounds/corridor\n二宫::走吧\n";
        let t = timeline(text);
        assert_eq!(t.nodes.len(), 1);
    }

    #[test]
    fn loc_marker_no_longer_splits_nodes_only_annotates_background() {
        let text = "#loc: backgrounds/room\n二宫::你好\n\n#loc: backgrounds/corridor\n二宫::走吧\n";
        let t = timeline(text);
        let m = moments(main_node(&t));
        assert_eq!(m.len(), 2);
        assert_eq!(m[0].background, Some("backgrounds/room".to_string()));
        assert_eq!(m[1].background, Some("backgrounds/corridor".to_string()));
    }

    #[test]
    fn background_is_sticky_within_a_node_same_as_before() {
        let text = "#loc: backgrounds/room\n二宫::你好\n张浅野::早\n";
        let t = timeline(text);
        let m = moments(main_node(&t));
        assert_eq!(m[0].background, Some("backgrounds/room".to_string()));
        assert_eq!(m[1].background, Some("backgrounds/room".to_string()));
    }

    #[test]
    fn treats_input_without_markers_as_single_node_with_unknown_background() {
        let text = "二宫::你好\n张浅野::早\n";
        let t = timeline(text);
        assert_eq!(t.nodes.len(), 1);
        let m = moments(main_node(&t));
        assert_eq!(m.len(), 2);
        assert_eq!(m[0].background, None);
    }

    #[test]
    fn tracks_on_stage_roster_growing_within_a_node() {
        let text = "二宫::你好\n张浅野::早\n";
        let t = timeline(text);
        let m = moments(main_node(&t));
        assert_eq!(m[1].on_stage, vec!["二宫".to_string(), "张浅野".to_string()]);
    }

    // --- #cast: explicit on-stage roster delta ---

    #[test]
    fn cast_marker_adds_and_removes_from_on_stage_roster() {
        let text = "#cast: +小王\n小王进来了。\n#cast: -小王\n小王走了。\n";
        let t = timeline(text);
        let m = moments(main_node(&t));
        assert_eq!(m[0].on_stage, vec!["小王".to_string()]);
        assert_eq!(m[1].on_stage, Vec::<String>::new());
    }

    #[test]
    fn cast_delta_is_a_no_op_when_already_in_stated_state() {
        let text = "#cast: +小王\n#cast: +小王\n场景描写。\n";
        let t = timeline(text);
        let m = moments(main_node(&t));
        assert_eq!(m[0].on_stage, vec!["小王".to_string()]);
    }

    #[test]
    fn cast_roster_resets_entering_a_node_marker_block() {
        let text = "#cast: +小王\n二宫::开场\n#branch:\n#opt: next | 继续\n#node: next\n新节点的旁白。\n";
        let t = timeline(text);
        let next = t.nodes.iter().find(|n| n.name.as_deref() == Some("next")).unwrap();
        let m = moments(next);
        assert_eq!(m[0].on_stage, Vec::<String>::new());
    }

    // --- #seq: performance sequence passthrough ---

    #[test]
    fn seq_span_collects_consecutive_raw_lines_into_one_passthrough_item() {
        let text = "#seq:\nline one\nline two\nline three\n#seq:\n";
        let t = timeline(text);
        let raw: Vec<&str> = main_node(&t)
            .items
            .iter()
            .filter_map(|item| match item {
                NodeItem::RawPassthrough(s) => Some(s.as_str()),
                NodeItem::Moment(_) => None,
            })
            .collect();
        assert_eq!(raw.len(), 1);
        assert_eq!(raw[0], "line one\nline two\nline three");
    }

    #[test]
    fn seq_span_preserves_blank_lines_verbatim_inside_passthrough() {
        let text = "#seq:\nline one\n\nline two\n#seq:\n";
        let t = timeline(text);
        let raw = match &main_node(&t).items[0] {
            NodeItem::RawPassthrough(s) => s.clone(),
            _ => panic!("expected passthrough"),
        };
        assert_eq!(raw, "line one\n\nline two");
    }

    #[test]
    fn seq_span_lines_are_not_parsed_as_dialogue_speaker_or_hint_or_loc_markers() {
        let text = "#seq:\n二宫::这行不是台词\n#hnt: 也不是提示\n#loc: 也不是背景\n#seq:\n";
        let t = timeline(text);
        assert!(t.distinct_speakers.is_empty());
        let m = moments(main_node(&t));
        assert!(m.is_empty());
        match &main_node(&t).items[0] {
            NodeItem::RawPassthrough(s) => {
                assert!(s.contains("二宫::这行不是台词"));
                assert!(s.contains("#hnt: 也不是提示"));
            }
            _ => panic!("expected passthrough"),
        }
    }

    #[test]
    fn empty_seq_marker_closes_an_open_span_and_resumes_normal_parsing() {
        let text = "#seq:\nraw content\n#seq:\n二宫::正常台词\n";
        let t = timeline(text);
        let m = moments(main_node(&t));
        assert_eq!(m.len(), 1);
        assert_eq!(m[0].text, "二宫::正常台词");
    }

    #[test]
    fn content_before_and_after_seq_span_parses_normally_as_moments() {
        let text = "二宫::之前\n#seq:\nraw\n#seq:\n二宫::之后\n";
        let t = timeline(text);
        let m = moments(main_node(&t));
        assert_eq!(m.len(), 2);
        assert_eq!(m[0].text, "二宫::之前");
        assert_eq!(m[1].text, "二宫::之后");
    }

    #[test]
    fn unclosed_seq_span_at_eof_still_yields_a_passthrough_item() {
        let text = "#seq:\nraw one\nraw two\n";
        let t = timeline(text);
        assert_eq!(main_node(&t).items.len(), 1);
        assert!(matches!(main_node(&t).items[0], NodeItem::RawPassthrough(_)));
    }

    // --- branching ---

    #[test]
    fn branch_marker_sets_node_terminator_to_branch() {
        let text = "二宫::要怎么办\n#branch:\n#opt: path_a | 走左边\n#opt: path_b | 走右边\n#node: path_a\n旁白::左边\n#node: path_b\n旁白::右边\n";
        let t = timeline(text);
        assert!(matches!(main_node(&t).terminator, NodeTerminator::Branch(_)));
    }

    #[test]
    fn branch_node_collects_multiple_opt_lines_in_order() {
        let text = "#branch:\n#opt: a | 选A\n#opt: b | 选B\n#node: a\n旁白::A\n#node: b\n旁白::B\n";
        let t = timeline(text);
        match &main_node(&t).terminator {
            NodeTerminator::Branch(opts) => {
                assert_eq!(opts.len(), 2);
                assert_eq!(opts[0].dest, "a");
                assert_eq!(opts[1].dest, "b");
            }
            _ => panic!("expected Branch terminator"),
        }
    }

    #[test]
    fn branch_node_generates_branch_call_with_mode_and_cond() {
        let text = "#branch:\n#opt: a | 选A | normal | \n#opt: b | | jump | v_flag > 1\n#node: a\n旁白::A\n#node: b\n旁白::B\n";
        let t = timeline(text);
        match &main_node(&t).terminator {
            NodeTerminator::Branch(opts) => {
                assert_eq!(opts[0].mode, Some("normal".to_string()));
                assert_eq!(opts[1].mode, Some("jump".to_string()));
                assert_eq!(opts[1].cond, Some("v_flag > 1".to_string()));
                assert_eq!(opts[1].text, None);
            }
            _ => panic!("expected Branch terminator"),
        }
    }

    #[test]
    fn option_marker_treats_missing_trailing_fields_as_none() {
        let text = "#branch:\n#opt: a\n#node: a\n旁白::A\n";
        let t = timeline(text);
        match &main_node(&t).terminator {
            NodeTerminator::Branch(opts) => {
                assert_eq!(opts[0].dest, "a");
                assert_eq!(opts[0].text, None);
                assert_eq!(opts[0].mode, None);
                assert_eq!(opts[0].cond, None);
            }
            _ => panic!("expected Branch terminator"),
        }
    }

    #[test]
    fn node_marker_starts_a_new_named_node_block() {
        let text = "二宫::开场\n#node: next\n旁白::新节点的内容\n";
        let t = timeline(text);
        assert_eq!(t.nodes.len(), 2);
        assert_eq!(t.nodes[1].name, Some("next".to_string()));
        assert_eq!(moments(&t.nodes[1])[0].text, "旁白::新节点的内容");
    }

    #[test]
    fn node_without_explicit_terminator_defaults_to_end() {
        let text = "#node: leaf\n旁白::到此为止\n";
        let t = timeline(text);
        assert!(matches!(t.nodes[1].terminator, NodeTerminator::End));
    }

    #[test]
    fn jump_marker_sets_node_terminator_to_jump() {
        let text = "#node: a\n旁白::A\n#jump: converge\n#node: converge\n旁白::汇合点\n";
        let t = timeline(text);
        let a = t.nodes.iter().find(|n| n.name.as_deref() == Some("a")).unwrap();
        assert_eq!(a.terminator, NodeTerminator::Jump("converge".to_string()));
    }

    #[test]
    fn two_branches_converging_via_jump_to_same_node_name() {
        let text = "#branch:\n#opt: a | 选A\n#opt: b | 选B\n#node: a\n旁白::A\n#jump: converge\n#node: b\n旁白::B\n#jump: converge\n#node: converge\n旁白::汇合\n";
        let t = timeline(text);
        let a = t.nodes.iter().find(|n| n.name.as_deref() == Some("a")).unwrap();
        let b = t.nodes.iter().find(|n| n.name.as_deref() == Some("b")).unwrap();
        assert_eq!(a.terminator, NodeTerminator::Jump("converge".to_string()));
        assert_eq!(b.terminator, NodeTerminator::Jump("converge".to_string()));
        assert!(t.nodes.iter().any(|n| n.name.as_deref() == Some("converge")));
    }

    #[test]
    fn orphan_node_never_referenced_by_any_opt_is_allowed() {
        let text = "二宫::开场\n#node: unused\n旁白::没人指向我\n";
        let t = derive_world_state_timeline(text, "ch1_autostage");
        assert!(t.is_ok());
    }

    #[test]
    fn opt_dest_referencing_node_declared_later_in_file_is_valid() {
        let text = "#branch:\n#opt: later | 走\n#node: later\n旁白::后面才声明\n";
        let t = derive_world_state_timeline(text, "ch1_autostage");
        assert!(t.is_ok());
    }

    // --- WorldStateError variants ---

    #[test]
    fn opt_without_preceding_branch_marker_returns_error() {
        let text = "#opt: a | 选A\n";
        let err = derive_world_state_timeline(text, "ch1_autostage").unwrap_err();
        assert!(matches!(err, WorldStateError::OptWithoutBranch { .. }));
    }

    #[test]
    fn opt_with_empty_dest_returns_error() {
        let text = "#branch:\n#opt:  | 选A\n";
        let err = derive_world_state_timeline(text, "ch1_autostage").unwrap_err();
        assert!(matches!(err, WorldStateError::EmptyOptDest { .. }));
    }

    #[test]
    fn branch_marker_with_zero_following_opt_lines_returns_error() {
        let text = "#branch:\n二宫::没有选项就接了句台词\n";
        let err = derive_world_state_timeline(text, "ch1_autostage").unwrap_err();
        assert!(matches!(err, WorldStateError::BranchWithNoOptions { .. }));
    }

    #[test]
    fn branch_marker_with_zero_options_at_eof_returns_error() {
        let text = "#branch:\n";
        let err = derive_world_state_timeline(text, "ch1_autostage").unwrap_err();
        assert!(matches!(err, WorldStateError::BranchWithNoOptions { .. }));
    }

    #[test]
    fn duplicate_node_name_returns_error() {
        let text = "#node: dup\n旁白::第一次\n#node: dup\n旁白::第二次\n";
        let err = derive_world_state_timeline(text, "ch1_autostage").unwrap_err();
        assert!(matches!(err, WorldStateError::DuplicateNodeName { .. }));
    }

    #[test]
    fn node_name_colliding_with_base_label_returns_duplicate_error() {
        let text = "#node: ch1_autostage\n旁白::撞名了\n";
        let err = derive_world_state_timeline(text, "ch1_autostage").unwrap_err();
        assert!(matches!(err, WorldStateError::DuplicateNodeName { .. }));
    }

    #[test]
    fn opt_dest_referencing_undeclared_node_returns_error() {
        let text = "#branch:\n#opt: nowhere | 走\n";
        let err = derive_world_state_timeline(text, "ch1_autostage").unwrap_err();
        assert!(matches!(err, WorldStateError::DanglingDest { .. }));
    }

    #[test]
    fn jump_dest_referencing_undeclared_node_also_returns_dangling_dest_error() {
        let text = "#jump: nowhere\n";
        let err = derive_world_state_timeline(text, "ch1_autostage").unwrap_err();
        assert!(matches!(err, WorldStateError::DanglingDest { .. }));
    }

    // --- skeleton builder ---

    #[test]
    fn skeleton_always_ends_with_is_end_closer() {
        let text = "二宫::你好\n";
        let skeleton = build_node_skeleton(&timeline(text), "ch1_autostage");
        assert!(skeleton.trim_end().ends_with("@<| is_end() |>"));
    }

    #[test]
    fn skeleton_main_node_label_uses_base_label_directly_no_numeric_suffix() {
        let text = "#loc: backgrounds/room\n二宫::你好\n\n#loc: backgrounds/corridor\n二宫::走吧\n";
        let skeleton = build_node_skeleton(&timeline(text), "ch1_autostage");
        assert!(skeleton.contains("label(\"ch1_autostage\""));
        assert!(!skeleton.contains("ch1_autostage_1"));
        assert!(!skeleton.contains("ch1_autostage_2"));
    }

    #[test]
    fn skeleton_named_node_uses_its_declared_name_as_label() {
        let text = "二宫::开场\n#node: my_node\n旁白::内容\n";
        let skeleton = build_node_skeleton(&timeline(text), "ch1_autostage");
        assert!(skeleton.contains("label(\"my_node\""));
    }

    #[test]
    fn skeleton_only_main_node_gets_is_unlocked_start() {
        let text = "二宫::开场\n#node: second\n旁白::内容\n";
        let skeleton = build_node_skeleton(&timeline(text), "ch1_autostage");
        assert_eq!(skeleton.matches("is_unlocked_start()").count(), 1);
    }

    #[test]
    fn skeleton_dialogue_line_order_preserved_within_a_node_spanning_multiple_backgrounds() {
        let text = "#loc: backgrounds/room\n二宫::第一句\n\n#loc: backgrounds/corridor\n张浅野::第二句\n";
        let skeleton = build_node_skeleton(&timeline(text), "ch1_autostage");
        let first = skeleton.find("二宫::第一句").unwrap();
        let second = skeleton.find("张浅野::第二句").unwrap();
        assert!(first < second);
        assert_eq!(skeleton.matches("is_end()").count(), 1);
    }

    #[test]
    fn skeleton_branch_terminator_emits_branch_call_with_all_dest_text_mode_cond_fields() {
        let text = "#branch:\n#opt: a | 选A | show | v_flag > 0\n#node: a\n旁白::A\n";
        let skeleton = build_node_skeleton(&timeline(text), "ch1_autostage");
        assert!(skeleton.contains("branch(["));
        assert!(skeleton.contains("dest=\"a\""));
        assert!(skeleton.contains("text=\"选A\""));
        assert!(skeleton.contains("mode=\"show\""));
        assert!(skeleton.contains("cond=\"v_flag > 0\""));
    }

    #[test]
    fn skeleton_branch_option_omits_absent_fields_from_emitted_dict() {
        let text = "#branch:\n#opt: a\n#node: a\n旁白::A\n";
        let skeleton = build_node_skeleton(&timeline(text), "ch1_autostage");
        let branch_line = skeleton.lines().find(|l| l.contains("dest=\"a\"")).unwrap();
        assert!(!branch_line.contains("text="));
        assert!(!branch_line.contains("mode="));
        assert!(!branch_line.contains("cond="));
    }

    #[test]
    fn skeleton_jump_terminator_emits_jump_to_call_with_dest() {
        let text = "#node: a\n旁白::A\n#jump: b\n#node: b\n旁白::B\n";
        let skeleton = build_node_skeleton(&timeline(text), "ch1_autostage");
        assert!(skeleton.contains("jump_to(\"b\")"));
    }

    #[test]
    fn passthrough_content_is_preserved_verbatim_in_skeleton() {
        let text = "#seq:\nshow(\"bg\", \"cgs/a\")\n二宫::手写的台词\n#seq:\n";
        let skeleton = build_node_skeleton(&timeline(text), "ch1_autostage");
        assert!(skeleton.contains("show(\"bg\", \"cgs/a\")\n二宫::手写的台词"));
    }

    #[test]
    fn passthrough_is_wrapped_with_seq_begin_end_comment_markers_in_their_own_lazy_blocks() {
        let text = "#seq:\nraw content\n#seq:\n";
        let skeleton = build_node_skeleton(&timeline(text), "ch1_autostage");
        assert!(skeleton.contains(&format!("<|\n{SEQUENCE_BEGIN_MARKER}\n|>")));
        assert!(skeleton.contains(&format!("<|\n{SEQUENCE_END_MARKER}\n|>")));
    }

    #[test]
    fn seq_markers_never_appear_as_bare_top_level_lines() {
        let text = "#seq:\nraw content\n#seq:\n";
        let skeleton = build_node_skeleton(&timeline(text), "ch1_autostage");
        for line in skeleton.lines() {
            if line.contains("vvn:seq") {
                assert!(line.trim() == SEQUENCE_BEGIN_MARKER || line.trim() == SEQUENCE_END_MARKER);
            }
        }
        // Every occurrence of the marker text must sit immediately inside its own `<| |>` block,
        // not as a standalone top-level line outside any block.
        let begin_pos = skeleton.find(SEQUENCE_BEGIN_MARKER).unwrap();
        let preceding = &skeleton[..begin_pos];
        assert!(preceding.trim_end().ends_with("<|"));
    }

    #[test]
    fn multi_node_skeleton_with_branch_and_two_converging_jump_targets_all_close_correctly() {
        let text = "#branch:\n#opt: a | 选A\n#opt: b | 选B\n#node: a\n旁白::A\n#jump: converge\n#node: b\n旁白::B\n#jump: converge\n#node: converge\n旁白::汇合\n";
        let skeleton = build_node_skeleton(&timeline(text), "ch1_autostage");
        assert_eq!(skeleton.matches("branch([").count(), 1);
        assert_eq!(skeleton.matches("jump_to(").count(), 2);
        assert_eq!(skeleton.matches("is_end()").count(), 1);
        assert_eq!(skeleton.matches("label(").count(), 4);
    }
}
